version: "3.8"

services:
  backend:
    build: ./backend
    container_name: quotepulse-backend
    ports:
      - "5151:8080"
  
  frontend:
    build: ./frontend
    container_name: quotepulse-frontend
    ports:
      - "4300:80"
    depends_on:
      - backend
